### ISSUE TITLE
[td-agent2] permission error on td-agent2

### ISSUE THREAD

**Issue by sonots** [treasure-data/td-agent#77]
OS: CentOS 6.2

Installing td-agent2 as

```
$ curl -L http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
```

The permission of gems directory becomes like

```
ls -ld /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
drwxrwxr-x 8 root root 4096  3月 24 17:17 2015 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
```

So, td-agent-gem install fails as followings:

```
$ td-agent-gem install fluent-plugin-bigquery
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/td-agent/embedded/lib/ruby/gems/2.1.0/ directory.
```

I can add `sudo`, but it will install gems as root. Writing /etc/td-agent/td-agent.conf as

```
<match **>
  type bigquery
</match>
```

results in an error as below because `td-agent` user can not read gems

```
Starting td-agent: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- google/api_client (LoadError)
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
```

Changing owner of directories succeeds:

```
sudo chown td-agent:td-agent -R  /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
```

FYI: The reason why loading `google/api_client` is because it's permission (and permissions of all files in the gem) is set as 

```
$ ls -l /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb
-rw-r----- 1 root root 27249  3月 24 18:19 2015 api_client.rb
```

**Comment by kenjiskywalker** [comment]
thank you sonots-san :+1:

**Comment by sonots** [comment]
If the owner and group of `/opt/td-agent/embedded/lib/ruby/gems/2.1.0/` are `td-agent` as default, we can install gems with proper permission by running td-agent-gem command as

```
sudo -u td-agent /usr/sbin/td-agent-gem install fluent-plugin-bigquery
```

**Comment by sonots** [comment]
Sorry, I mistook the repository, re-issued https://github.com/treasure-data/omnibus-td-agent/issues/35
